name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Check Format
        run: mise run format

      - name: Lint code
        run: mise run lint

      - name: Run tests
        run: mise run test

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml

      - name: Update package versions to 0.0.0 for CI
        run: mise run update-version 0.0.0

      - name: Build packages
        run: mise run build

      - name: Publish to PyPI 0.0.0 version
        run: mise run publish ${{ secrets.PYPI_API_TOKEN }} --dry-run
